### ISSUE TITLE
Accelerometer data shifting unexpectedly

### ISSUE THREAD

**Issue by micahjohnson150** [AdventureData/radicl#6]
* radicl version: 0.3.2
* Firmware version (if applicable): 1.45.3.2
* Python version: 3.6
* Operating System: Linux

### Description

Sometimes when I get accelerometer data from the probe this is what I see. It seems to me that the accelerometer data is shifting? Not sure. Here is what it looks like:
![acceleration_data_drop](https://user-images.githubusercontent.com/7646021/75254717-07785f80-579e-11ea-9925-5f9a7208b2a9.png)

### What I Did

In the above measurement I lightly move the probe side to side with the tip on the ground.

**Comment by arothenbuhler** [comment]
Do you have a data file that you can send me? I'd like to take a look at the raw numbers. Have some ideas...

**Comment by micahjohnson150** [comment]
I don't but I will create one and send it. Are your ideas related to radicl
or firmware?

**Comment by arothenbuhler** [comment]
They are related to firmware. It could be an overflow or data type issue, so I'd like to check the raw data. If the change is gradual over 2-3 samples, then that would indicate real and correct data, but if the change is sudden and drops over an order of magnitude then that indicates a possible overflow/data type issue.

One thing that I would like to have more clarification on is what the real problem actually is. It looks like there are a lot of very dramatic moves up and down on the blue line. Is that the issue? Or is it that the blue line (X-Axis) ends at a much different level?

Also, what does it look like if you do the same experiment in the air? Meaning that the board/probe doesn't actually touch a table. I'd expect the graph to be a little smoother.

**Comment by micahjohnson150** [comment]
Here is me moving it up and down.

![Figure_1](https://user-images.githubusercontent.com/7646021/75313706-ce320500-581a-11ea-83ba-6051c899d953.png)

[2020-02-25--220308.txt](https://github.com/AdventureData/radicl/files/4253484/2020-02-25--220308.txt)

**Comment by micahjohnson150** [comment]
@arothenbuhler I got you the putty log version of this. Puttylog attached showing settings.

[acc_putty_log.txt](https://github.com/AdventureData/radicl/files/4268177/acc_putty_log.txt)

![putty_accelerometer_data](https://user-images.githubusercontent.com/7646021/75569395-3991f780-5a12-11ea-8eb5-5c15ae103447.png)

**Comment by arothenbuhler** [comment]
Haha, I know what the issue is... I'm assuming the graph you just posted is based on the attached putty log, right?
If you look at the numbers, they are positive and negative, which means signed data type. When it's sent across with the API and then reassembled on the other end, it's forced into a signed data type....
My mistake, sorry. Only affects radicl, probe FW is fine. I'll try to get to this ASAP.
Can you confirm though that the above graph is what you would expect?

**Comment by micahjohnson150** [comment]
The data is directly from the log. I wrote a little script to quickly plot it.  The data is what I expected for the movement. I am not sure on the range of values in the Y axis of the plot.
Do you mean forced into an unsigned in the API?

**Comment by arothenbuhler** [comment]
Yes, the API forces it into an UNsigned data type. Sorry for my typo.
I'm assuming that the Y-axis was actually the Z-axis the way you held the probe. The data should be post-processed a bit to get it into the correct range. I have been putting this off for too long and will add it to the API. What you're seeing on the Y-axis is a -1g (normal gravity) pull towards earth. I am making the assumption that you moved the probe horizontally.

**Comment by micahjohnson150** [comment]
yeah I pivoted it side to side with the tip on the ground with the pole held vertically.
